module ImplementedFunctions exposing (..)

{-| Thank you mbylstra for the code from this repo: <https://github.com/mbylstra/html-to-elm/blob/c3c4b9a3f8c8c8b15150bd04f72ad89c4b11462e/elm-src/HtmlToElm/ElmHtmlWhitelists.elm>
-}


lookup : List String -> String -> Maybe String
lookup list name =
    let
        lowerName =
            String.toLower name
    in
    find (\entry -> String.toLower entry == lowerName) list


find : (a -> Bool) -> List a -> Maybe a
find predicate list =
    case list of
        [] ->
            Nothing

        first :: rest ->
            if predicate first then
                Just first

            else
                find predicate rest


cssHelpers : List String
cssHelpers =
    [ "focus"
    , "group"
    , "hover"
    ]


htmlTags =
    [ "body"
    , "section"
    , "nav"
    , "article"
    , "aside"
    , "h1"
    , "h2"
    , "h3"
    , "h4"
    , "h5"
    , "h6"
    , "header"
    , "footer"
    , "address"
    , "p"
    , "hr"
    , "pre"
    , "blockquote"
    , "ol"
    , "ul"
    , "li"
    , "dl"
    , "dt"
    , "dd"
    , "figure"
    , "figcaption"
    , "div"
    , "a"
    , "em"
    , "strong"
    , "small"
    , "s"
    , "cite"
    , "q"
    , "dfn"
    , "abbr"
    , "time"
    , "code"
    , "var"
    , "samp"
    , "kbd"
    , "sub"
    , "sup"
    , "i"
    , "b"
    , "u"
    , "mark"
    , "ruby"
    , "rt"
    , "rp"
    , "bdi"
    , "bdo"
    , "span"
    , "br"
    , "wbr"
    , "ins"
    , "del"
    , "img"
    , "iframe"
    , "embed"
    , "object"
    , "param"
    , "video"
    , "audio"
    , "source"
    , "track"
    , "canvas"
    , "svg"
    , "math"
    , "table"
    , "caption"
    , "colgroup"
    , "col"
    , "tbody"
    , "thead"
    , "tfoot"
    , "tr"
    , "td"
    , "th"
    , "form"
    , "fieldset"
    , "legend"
    , "label"
    , "input"
    , "button"
    , "select"
    , "datalist"
    , "optgroup"
    , "option"
    , "textarea"
    , "keygen"
    , "output"
    , "progress"
    , "meter"
    , "details"
    , "summary"
    , "menuitem"
    , "menu"
    ]


svgTags =
    [ "defs"
    , "clipPath"
    , "path"
    , "g"
    , "svg"
    , "path"
    ]


htmlAttributes =
    [ "key"
    , -- "style",   -- style is disabled as it requires special parsing
      "class"
    , "classList"
    , "id"
    , "title"
    , "type_"
    , "value"
    , "placeholder"
    , "accept"
    , "acceptCharset"
    , "action"
    , "autosave"
    , "enctype"
    , "formaction"
    , "list"
    , "method"
    , "name"
    , "pattern"
    , "for"
    , "form"
    , "max"
    , "min"
    , "step"
    , "wrap"
    , "href"
    , "target"
    , "downloadAs"
    , "hreflang"
    , "media"
    , "ping"
    , "rel"
    , "usemap"
    , "shape"
    , "coords"
    , "src"
    , "alt"
    , "preload"
    , "poster"
    , "kind"
    , "srclang"
    , "sandbox"
    , "srcdoc"
    , "align"
    , "headers"
    , "scope"
    , "charset"
    , "content"
    , "httpEquiv"
    , "language"
    , "accesskey"
    , "contextmenu"
    , "dir"
    , "draggable"
    , "dropzone"
    , "itemprop"
    , "lang"
    , "challenge"
    , "keytype"
    , "cite"
    , "datetime"
    , "pubdate"
    , "manifest"
    , "property"
    , "attribute"
    ]


svgAttributes =
    [ "accent-height"
    , "accelerate"
    , "accumulate"
    , "additive"
    , "alphabetic"
    , "allowReorder"
    , "amplitude"
    , "arabic-form"
    , "ascent"
    , "attributeName"
    , "attributeType"
    , "autoReverse"
    , "azimuth"
    , "baseFrequency"
    , "baseProfile"
    , "bbox"
    , "begin"
    , "bias"
    , "by"
    , "calcMode"
    , "cap-height"
    , "class"
    , "clipPathUnits"
    , "contentScriptType"
    , "contentStyleType"
    , "cx"
    , "cy"
    , "d"
    , "decelerate"
    , "descent"
    , "diffuseConstant"
    , "divisor"
    , "dur"
    , "dx"
    , "dy"
    , "edgeMode"
    , "elevation"
    , "end"
    , "exponent"
    , "externalResourcesRequired"
    , "filterRes"
    , "filterUnits"
    , "format"
    , "from"
    , "fx"
    , "fy"
    , "g1"
    , "g2"
    , "glyph-name"
    , "glyphRef"
    , "gradientTransform"
    , "gradientUnits"
    , "hanging"
    , "height"
    , "horiz-adv-x"
    , "horiz-origin-x"
    , "horiz-origin-y"
    , "id"
    , "ideographic"
    , "in"
    , "in2"
    , "intercept"
    , "k"
    , "k1"
    , "k2"
    , "k3"
    , "k4"
    , "kernelMatrix"
    , "kernelUnitLength"
    , "keyPoints"
    , "keySplines"
    , "keyTimes"
    , "lang"
    , "lengthAdjust"
    , "limitingConeAngle"
    , "local"
    , "markerHeight"
    , "markerUnits"
    , "markerWidth"
    , "maskContentUnits"
    , "maskUnits"
    , "mathematical"
    , "max"
    , "media"
    , "method"
    , "min"
    , "mode"
    , "name"
    , "numOctaves"
    , "offset"
    , "operator"
    , "order"
    , "orient"
    , "orientation"
    , "origin"
    , "overline-position"
    , "overline-thickness"
    , "panose-1"
    , "path"
    , "pathLength"
    , "patternContentUnits"
    , "patternTransform"
    , "patternUnits"
    , "point-order"
    , "points"
    , "pointsAtX"
    , "pointsAtY"
    , "pointsAtZ"
    , "preserveAlpha"
    , "preserveAspectRatio"
    , "primitiveUnits"
    , "r"
    , "radius"
    , "refX"
    , "refY"
    , "rendering-intent"
    , "repeatCount"
    , "repeatDur"
    , "requiredExtensions"
    , "requiredFeatures"
    , "restart"
    , "result"
    , "rotate"
    , "rx"
    , "ry"
    , "scale"
    , "seed"
    , "slope"
    , "spacing"
    , "specularConstant"
    , "specularExponent"
    , "speed"
    , "spreadMethod"
    , "startOffset"
    , "stdDeviation"
    , "stemh"
    , "stemv"
    , "stitchTiles"
    , "strikethrough-position"
    , "strikethrough-thickness"
    , "string"
    , "style"
    , "surfaceScale"
    , "systemLanguage"
    , "tableValues"
    , "target"
    , "targetX"
    , "targetY"
    , "textLength"
    , "title"
    , "to"
    , "transform"
    , "type"
    , "u1"
    , "u2"
    , "underline-position"
    , "underline-thickness"
    , "unicode"
    , "unicode-range"
    , "units-per-em"
    , "v-alphabetic"
    , "v-hanging"
    , "v-ideographic"
    , "v-mathematical"
    , "values"
    , "version"
    , "vert-adv-y"
    , "vert-origin-x"
    , "vert-origin-y"
    , "viewBox"
    , "viewTarget"
    , "width"
    , "widths"
    , "x"
    , "x-height"
    , "x1"
    , "x2"
    , "xChannelSelector"
    , "y"
    , "y1"
    , "y2"
    , "yChannelSelector"
    , "z"
    , "zoomAndPan"
    , "alignment-baseline"
    , "baseline-shift"
    , "clip-path"
    , "clip-rule"
    , "clip"
    , "color-interpolation-filters"
    , "color-interpolation"
    , "color-profile"
    , "color-rendering"
    , "color"
    , "cursor"
    , "direction"
    , "display"
    , "dominant-baseline"
    , "enable-background"
    , "fill-opacity"
    , "fill-rule"
    , "fill"
    , "filter"
    , "flood-color"
    , "flood-opacity"
    , "font-family"
    , "font-size-adjust"
    , "font-size"
    , "font-stretch"
    , "font-style"
    , "font-variant"
    , "font-weight"
    , "glyph-orientation-horizontal"
    , "glyph-orientation-vertical"
    , "image-rendering"
    , "kerning"
    , "letter-spacing"
    , "lighting-color"
    , "marker-end"
    , "marker-mid"
    , "marker-start"
    , "mask"
    , "opacity"
    , "overflow"
    , "pointer-events"
    , "shape-rendering"
    , "stop-color"
    , "stop-opacity"
    , "stroke-dasharray"
    , "stroke-dashoffset"
    , "stroke-linecap"
    , "stroke-linejoin"
    , "stroke-miterlimit"
    , "stroke-opacity"
    , "stroke-width"
    , "stroke"
    , "text-anchor"
    , "text-decoration"
    , "text-rendering"
    , "unicode-bidi"
    , "visibility"
    , "word-spacing"
    , "writing-mode"
    ]


toCamelCase : String -> String
toCamelCase name =
    case name |> String.split "-" of
        [] ->
            ""

        head :: tail ->
            tail
                |> List.map capitalize
                |> (::) head
                |> String.join ""


capitalize : String -> String
capitalize string =
    case String.uncons string of
        Just ( headChar, tailString ) ->
            String.cons (Char.toUpper headChar) tailString

        Nothing ->
            string



-- not currently used


boolAttributeFunctions =
    [ "hidden"
    , "checked"
    , "selected"
    , "autocomplete"
    , "autofocus"
    , "disabled"
    , "multiple"
    , "novalidate"
    , "readonly"
    , "required"
    , "download"
    , "ismap"
    , "autoplay"
    , "controls"
    , "loop"
    , "default"
    , "seamless"
    , "reversed"
    , "async"
    , "defer"
    , "scoped"
    , "contenteditable"
    , "spellcheck"
    ]



-- not currently used


intAttributeFunctions =
    [ "maxlength"
    , "minlength"
    , "size"
    , "cols"
    , "rows"
    , "height"
    , "width"
    , "start"
    , "colspan"
    , "rowspan"
    , "tabindex"
    ]


reservedWords =
    [ "main"
    , "type"
    ]
